"use client"

import { nanoid } from '@/lib/utils'
import { GetServerSideProps } from 'next'
import RootLayout from '../app/layout'; // Adjust the path based on your directory structure
import { Toaster } from 'react-hot-toast'

import '../app/globals.css'
import { useState, useCallback } from 'react';
import { fontMono, fontSans } from '@/lib/fonts'
import { cn } from '../lib/utils'
import { Providers } from '@/components/providers'
import { Header } from '@/components/header'
import { useToasts } from '@geist-ui/core'
import Head from 'next/head';
import MessageInput from '../tools/messageInput'


const runtime = 'edge'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { cam } = context.query;
  console.log(`🚨 context`, context)
  if(cam) {
    console.log(cam);
  }

  const id = nanoid()

  return {
    props: {
      id,
      add: cam ? cam.toString() : null,
    },
  }
}

interface UpProps {
  id: string;
  cam: string | null;
}

const Up: React.FC<UpProps> = ({ id, cam }) => {

    const [metadata, setMetadata] = useState("");
    const [inputText, setInputText] = useState("");
    const [isLoading, setIsLoading] = useState(false);

    const { setToast } = useToasts()
    const action = {
      name: 'cancel',
      passive: true,
      handler: (cancel: any) => cancel()
    }

    const handleSendMessage = useCallback( async () => {

        if(inputText.trim() !== "" && !isLoading ){
            setIsLoading(true);
            console.log(`inputText`, inputText)
            try {
                const call = await fetch("http://localhost:5025/api/v1/vector/addCollection", {
                    method: "POST",
                    body: JSON.stringify({
                        transcript: inputText.trim(),
                        metadata: JSON.stringify(metadata),
                    }),
                    headers: { "Content-Type": "application/json" },
                });
    
                if(call.status === 200 && call.statusText === "OK" ){
                  
    
                    const pineconeData = await call.json()
                    const quantityAdded = pineconeData.added
                    const quantityDuplicated = pineconeData.duplicates
    
                    const contentAdded = pineconeData.vectorsAdded
                    const contentDuplicated = pineconeData.duplicatesAdded
    
                    console.log(`pineconeData)`, pineconeData);
    
                    if(quantityAdded > 0){
                      setToast({ text: `🚨 ${quantityAdded} chunk(s) of new data added to Pinecone!` })
                      setToast({ text: `🗄️ ${contentAdded}!` })
                      setInputText("");
                      setMetadata("");
                    } else if (quantityAdded === 0){
                      if(quantityDuplicated > 0){
                        setToast({ text: `🚨 ${quantityDuplicated} chunk(s) of data already exists in Pinecone!` })
                        setToast({ text: `🗄️ ${contentDuplicated}!` })
                        setInputText("");
                        setMetadata("");
                      } else {
                        setToast({ text: `🚨 hmmm something's up, no data was added but there also wasn't a duplicate in Pinecone` })
                      }
                    }
    
                    
                  }
               
            } catch (error) {
                console.error("Error: ", error);
                setIsLoading(false);
                // setInputText("")
            }
            setIsLoading(false)
        }
    }, [metadata, inputText, isLoading]);


  return  (
    <div className={cn(
        'font-sans antialiased',
        fontSans.variable,
        fontMono.variable
      )}>
     <Head>
        <title>Upload Data to MH</title>
        <meta name="description" content="Generated by Cam Burley" />
        <link rel="icon" href="https://stripe-camo.global.ssl.fastly.net/2602c0865c071384d056ccec257f10942041865c5dccdc5a32f3aae7b76e7c93/68747470733a2f2f66696c65732e7374726970652e636f6d2f6c696e6b732f4d44423859574e6a64463878516c6c784d464a4663585a52626e56326247395866475a7358327870646d56665231597a4f444275634856716430314a576c41784e5452585a4568314e454e31303050504b577241624a/6d65726368616e745f69643d616363745f314259713052457176516e75766c6f5726636c69656e743d5041594d454e545f50414745" />
      </Head> 
    <Providers attribute="class" defaultTheme="light" enableSystem>
      <div className="flex flex-col min-h-screen">
        {/* @ts-ignore */}
        
        <header className="sticky top-0 z-50 flex items-center justify-between w-full h-16 px-4 border-b shrink-0 bg-gradient-to-b from-background/10 via-background/50 to-background/80 backdrop-blur-xl">
        <div className="flex items-center">
        <>Add to Knowledge Base</>
        </div>
        </header>

        <main className="flex flex-col flex-1 bg-muted/50">
            <div style={{ marginTop: '100px'}} ></div>
        <MessageInput 
        handleSendMessage={handleSendMessage} 
        setInputText={setInputText} 
        inputText={inputText} 
        metadata={metadata} 
        setMetadata={setMetadata} 
        isLoading={false}
        />
        
        </main>
      </div>
    </Providers>
    </div>
)
}

export default Up;